# Generated by Django 5.1.4 on 2025-01-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uername',
            new_name='username',
        ),
    ]
